<?php
/**
 * Implements hook_node_info()
 *//*
function conosur_menu() {
    
    $items['resultado/%/%'] = array(
        'title' => 'derma',
        'page callback' => 'page_resultado_derma',
        'page arguments' => array(1, 2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'derma.pages.inc',
        );
 return $items;
}*/
/**
 * Implements hook_preprocess_page()
 */
function conosur_preprocess_page (&$vars, $hook) {
    $argUno =  arg(0);
    if ($argUno == 'node') {
        $tipe = get_type_node (arg(1));
        if ($tipe == "page") {
            $img_field = get_field_data_img_custom(arg(1), "background", 0, 1);
            if (isset($img_field[0]['uri'])) {
                $og_img_color = image_style_url("img1280x600", $img_field[0]['uri']);
                $nid_ = arg(1);
                drupal_add_css(
                    '.page-node-' . $nid_ . ' .bg-page {background-image: url("'. $og_img_color.'")!important;}
                    .bg-page .bg {background-image: url("'. $og_img_color.'");}',
                    array(
                      'group' => CSS_THEME,
                      'type' => 'inline',
                      'media' => 'screen',
                      'preprocess' => FALSE,
                      'weight' => '9999',
                    )
                  );
            }
        }
        
    }
}
function conosur_block_info(){
    $block['block_up_header'] = array(
        'info' => t('Reder sociales header superior'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $block['block_menu_nosotros'] = array(
        'info' => t('bloque menu nosotros'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $block['block_register_user'] = array(
        'info' => t('bloque registrar usuarios'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $block;
}
/**
 * Block register callback
 */
function conosur_block_register_callback() {
   $reg_form = drupal_get_form('user_register_form');
   $output = drupal_render($reg_form);
   return $output;
}
/**
 * Implements hook_block_view(). $nodequeue = nodequeue_load_nodes(26);
 */
function conosur_block_view($block_key){
    $block = array();
    switch ($block_key){ 
        case 'block_register_user':
            $block['subject'] = t('NUEVO CLIENTE');
            $block['content'] = conosur_block_register_callback();
            break;
        case 'block_menu_nosotros':
            $items = array();
            $menu_tree = menu_tree_all_data('menu-nosotros');
            $menu_tree_output = menu_tree_output($menu_tree);
            foreach($menu_tree_output as $item_id => $item_data) {
                if(is_numeric($item_id) && is_array($item_data)) {
                    $items[] = l('<span>' . $item_data['#title'] . '</span>', $item_data['#href'], array(
                            'attributes'    => $item_data['#attributes'],
                            'html'      => TRUE,
                        )
                    );
                }
            }
            $attributes = array(
                'id' => "menu-lateral",
                'class' => 'nav navbar-nav navbar-right sombraList', 
                );
            $boton = '<div class="clear"><button id="navbar-toggle-nosotros" type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button></div>';
            $block['content'] = $boton . '<nav class="navbar " role="navigation">
                        <div class="container-fluid">' .
                      theme('item_list', array('items' => $items, 'type' => 'ul','attributes' => $attributes)).
                      '</div>
                          </nav>';
            break;
        case 'block_up_header':
            global $user;
            $registroUrl = "";
            $path = current_path();
            $path_alias = drupal_lookup_path('alias',$path);
            if ($user->uid == 0){
                $registroUrl = l(" ", get_url_page() . "user/register" ,array('attributes' => array('class' => array('likn-registro-header'),'title'=>"CONOSUR")));
            } else {
                $registroUrl = l(" ", get_url_page() .url ('user/' . $user->uid ) ,array('attributes' => array('class' => array('likn-registro-header-registrado'),'title'=>"CONOSUR")));
            }
            $path = current_path();
            $path_alias = drupal_lookup_path('alias',$path);    
            $variables = array(
                'youtube'=> l("", 'https://www.youtube.com/watch?v=FdMI3mJnv9k', array('attributes' => array('class' => array('likn-item youtubeTop'),'target' => '_blank','title'=>"Share This on twitter"))),
                'instagram'=> l("", 'http://instagram.com/',array('attributes' => array('class' => array('likn-item instagram'),'target' => '_blank','title'=>"Share This on twitter"))),
                'twitter'=> l(" ", "https://twitter.com/share?url=" .  get_url_page() . $path_alias . "&text=DERMA",array('attributes' => array('class' => array('likn-item twitterTop'),'target' => '_blank','onClick'=>"return Drupal.behaviors.socialMedia.fbs_click(400, 300,'twitter')",'title'=>"Share This on twitter"))),
                'facebook'=> l(" ",  "http://www.facebook.com/share.php?u=" .get_url_page() . $path_alias,array('attributes' => array('class' => array('likn-item' ,'facebookTop'),'onClick'=>"return Drupal.behaviors.socialMedia.fbs_click(400, 300,'facebook')", 'target'=>"_blank", 'title'=>"Share This on Facebook"  ))),
                'link-registro' => $registroUrl,
                );
            $block['subject'] = NULL;
            $block['content'] = array(
            '#theme' => 'block_up_header',
            '#items' => $variables,
            '#attached' => array(
                'js' => array(
                    array(
                        'data' => drupal_get_path('module', 'conosur') . '/js/social_media.js',
                      ),
                    ),
                )    
            );
            break;
    }   
    return $block;
}
function conosur_theme(){
    return array(
        'block_up_header' => array(
            'template' => 'theme/block_up_header',
            'variables' => array(
                'items' => array()
                )
            ),
        );
}

function get_type_node ($nid) {
    $arraydatos = "";
    $query = db_select('node', 'n');    
    $query->fields('n', array('type'))->condition('n.nid', $nid,'=');
    $result= $query->execute();
    while ($row = $result->fetchAssoc()) {
        $arraydatos = $row["type"];
    }
    return $arraydatos;
}
/**
 * consulta sql retorna imagens contenido
 * @param type $entity_id
 * @param type $img
 * @param type $limit_inf
 * @param type $limit_sup
 * @return type
 */
function get_field_data_img_custom($entity_id, $img, $limit_inf=FALSE, $limit_sup=FALSE) {
    $arraydatos = array();
    $query = db_select('field_data_field_' . $img, 'v');
    $query->join('file_usage', 'fu', 'v.field_' . $img . '_fid = fu.fid'); 
    $query->join('file_managed', 'm', 'fu.fid = m.fid');    
    $query->fields('m', array('filename','uri'))
    	  ->fields('v', array('field_' . $img . '_alt','field_' . $img . '_title'))
    	  ->condition('v.entity_id', $entity_id, '=');
    $query->orderBy('v.delta', "ASC");
    if ($limit_inf && $limit_sup) {
        $query->range($limit_inf, $limit_sup);      
    }    
    $result = $query->execute();
    while ($row = $result->fetchAssoc()) {
        $arraydatos[] = array(
            "uri" => $row["uri"], 
            "filename" => $row["filename"],
            "field_" . $img . "_alt" => $row["field_" . $img . "_alt"],
            "field_" . $img . "_title" => $row["field_". $img ."_title"],
        );
    }
    return $arraydatos;
}
function get_url_page(){
    global $base_url;
    $url=  $base_url.'/';//"http://".$_SERVER['HTTP_HOST'] .
    return $url;
}